# Site settings
title: marcelomesmo
email: marcelo.barbosa@ifrn.edu.br
url: https://marcelomesmo.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
meta_author: de Barros Marcelo

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: marcelomesmo

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f46a50 #80B3FF
  primary-rgb: "244,106,80" #"128,179,255"
  secondary: 4c4147 #FD6E8A
  secondary-dark: 352b31 #A2122F

google_verify: 
bing_verify:

# Footer settings
footer:
  copyright: Marcelo de Barros
  contact: Contact Me
  social: Around the Web
  tools: Tools

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/marcelomesmo
  - title: artstation
    url: https://www.artstation.com/marcelomesmo
  - title: github
    url: http://github.com/marcelomesmo

# Postal address (add as many lines as necessary)
contact: 
  - email: marcelo.barbosa [at] ifrn.edu.br

# Credits content
tools: 
  - line: Sublime Text
  - line: Construct 2/3
  - line: Aseprite
  - line: Photoshop
  - line: C++ C# Groovy

# Build settings
markdown: kramdown
permalink: pretty
